# Generated by Django 5.0.1 on 2024-05-18 11:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("file_versions", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="User",
        ),
    ]
