# Generated by Django 5.0.1 on 2024-05-18 17:02

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("file_versions", "0003_file_document"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(
                    2024, 5, 18, 16, 58, 0, 989737, tzinfo=datetime.timezone.utc
                ),
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="document",
            name="file_location",
            field=models.CharField(default="/bc/ad.pdf", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="document",
            name="modified_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="file",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="file",
            name="digest",
            field=models.CharField(
                default="3ef729ccf0cc56079ca546d58083dc12", max_length=32
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="file",
            name="modified_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="document",
            name="file",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="file_versions.file"
            ),
        ),
    ]
