# Generated by Django 5.0.1 on 2024-05-19 11:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("file_versions", "0005_alter_document_file_location_alter_file_digest"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="file_location",
            field=models.CharField(max_length=255),
        ),
    ]
