# Generated by Django 5.0.1 on 2024-05-19 16:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("file_versions", "0006_alter_document_file_location"),
    ]

    operations = [
        migrations.AlterField(
            model_name="file",
            name="digest",
            field=models.CharField(max_length=32),
        ),
    ]
